### ISSUE TITLE
[feat]: 点击`blog`的时，应切换对应地址

### ISSUE THREAD

**Issue by RSS1102** [shuimo-design/shuimo-blog#2]
![image](https://github.com/shuimo-design/shuimo-blog/assets/81673017/ace4912f-d96d-42aa-a74b-0d383ca1c300)
![image](https://github.com/shuimo-design/shuimo-blog/assets/81673017/c78f22cf-9104-4a58-a462-b59bc0678e78)

**Comment by higuaifan** [comment]
I plan for the next big version to be similar in nature to `topics(maybe hashtag?)`,
For example:
`#javascript #typescript #vite #vue #shuimo`
a `blog` may contain multiple entries, but perhaps classification is equally important.
But I haven't thought about whether it is better to use `primary and secondary entries` or `classification + entries`.
It can be discussed.

-----

下个大版本我计划它的性质类似于词条，
例如
`#javascript #typescript #vite #vue #shuimo`
一个`blog`可能包含了多个词条，但或许分类也同样重要，
但我没想好是`主次词条`更好，还是`分类+词条`更好。
可以讨论一下。

**Comment by RSS1102** [comment]
更倾向于 `core`/`分类`/`page`
`分类`: 就像文件夹一样，是归于本类别的某个文件
`词条`: 词条可能会根据内容的修改调整，涉及的范围不同，词条可能会有增减，会导致一个blog的链接不保持唯一性了。
