### ISSUE TITLE
[bug]: `menu` 菜单未提供选择回显

### ISSUE THREAD

**Issue by RSS1102** [shuimo-design/shuimo-blog#4]
![image](https://github.com/shuimo-design/shuimo-blog/assets/81673017/55ab01dc-93bf-4fe1-bdb1-65809013ad51)

**Comment by higuaifan** [comment]
What does "菜单未提供选择回显" mean?
------
“ 菜单未提供选择回显”是什么意思？

**Comment by RSS1102** [comment]
当前路由为`root/friends`, 但是在菜单项上未有一个`item`被选中。

**Comment by higuaifan** [comment]
You're right, but this is also a design 🐶. It can't be regarded as a `bug', you can `PR`.
---
你说的对但是这也是一种设计🐶，不能算`bug`，你`PR`吧。
